---
version: “3”
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      # DB_HOST: ${DB_HOST}
      # DB_PORT: ${DB_PORT}
      # DB_USERNAME: ${DB_USERNAME}
      # DB_PASSWORD: ${DB_PASSWORD}
    command: npm run start:dev
    depends_on:
      - db
      # - redis
      # - vault
  db:
    image: postgres:12
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_USER: ${DB_USERNAME}
      # POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # redis:
  #   image: redis:latest
  #   ports:
  #     - “6379:6379"
  # # TODO: Disable the dev mode in production
  # vault:
  #   image: vault:1.13.3
  #   container_name: vault
  #   ports:
  #     - “8200:8200”
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: myroot
  #     VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
  #   cap_add:
  #     - IPC_LOCK
volumes:
  postgres_data:
